### ISSUE TITLE
i modified the python api in python3, but encounter some error

### ISSUE THREAD

**Issue by fei12358** [Caesar11/gStore#24]
```
Traceback (most recent call last):
command to send to server:
  File "D:/Projects/pcProject/conv_txt/example/PythonAPIExample.py", line 9, in <module>
load LUBM10
    gc.load('LUBM10')
  File "C:\python\GstoreConnector.py", line 92, in wrapper
    if not self._send(full_cmd):
  File "C:\python\GstoreConnector.py", line 30, in _send
    data = self._pack(msg)
  File "C:\python\GstoreConnector.py", line 50, in _pack
    data_context.extend(msg)
TypeError: an integer is required
```

want some help^-^

**Comment by bookug** [comment]
which file do you modified? GstoreConnector.py or PythonAPIExample.py? It seems that there exist some bugs about format in your python code...

**Comment by bookug** [comment]
Email your modifications to me and I will check it: zengli@bookug.cc

**Comment by fei12358** [comment]
I send it to you. Thank you for your check.
